### ISSUE TITLE
rs with s6 doesn't display status correctly

### ISSUE THREAD

**Issue by vladimir-lu** [tokiclover/supervision#1]
Maybe I'm not using it correctly - but with r36 - using s6 with init-stage-1 on gentoo running:
1. `rs <service> add`
2. `rs <service> start`
3. `rs <service> status`

Shows the service as stopped even though it's running as verified with ps.

But this may be due to the fact that starting shows an error also:

`[syslog] service start: s6-svc: usage: s6-svc [ -wu | -wU | -wd | -wD | -wr | -wR ] [ -T timeout ] [ -abqhkti12pcoduxOX ] servicedir`

It could well be something strange in my setup.

**Comment by vladimir-lu** [comment]
s6 is at version 2.2.4.3

**Comment by tokiclover** [comment]
First, please upgrade to r37 because there are a few important fixes.

Second, some commands does not make any sense if no `--rs|--sv` like `add` (to add a service to a run level). Without `--rs|--sv` (what service type) and `-[0123]` for where; there is no way to get what you want without specifying exactly what/where to do. This can be improved in future release (better error handlings).

Lastly, I did test everything with runit but not s6 and it seems I shall upgrade `-U -T 10000` to `-wU -T10000` and `-D -T 10000` to `-wD -T10000` (in `sv/.lib/bin/sv-config` and `sv/.opt/SVC_BACKEND` for you unless you sync to the latest git.)

Finaly, I will add something to get a few commands working for supervision (`--sv`) backend.

So yes, the status command is affirmative in the sense that it seems service start was not marked correctly.
