### ISSUE TITLE
klog messages don't get updated after booting

### ISSUE THREAD

**Issue by vladimir-lu** [tokiclover/supervision#2]
Again, using s6, openrc, gentoo and socklog as the logging backend - there is no socklog-klog support in the bundle currently. Is it just a case of adding the appropriate switch statement in the `run` file? 

If so I can give it a go once #1 is fixed and make a PR.

**Comment by tokiclover** [comment]
Err yes... it's juts a matter of adding `sv/syslog/OPTIONS.socklog-klog`; and then set `name=socklog-klog` in `sv/syslog/OPTIONS`'s `case`, so that, every damon depending on `syslog` will get the right thing.

No run/finsh editing with this package; it's rather `OPTIONS` editing.

And it seems that [socklog-klog](http://apt-browse.org/browse/debian/wheezy/main/all/socklog-run/2.1.0-8/file/etc/sv/socklog-klog/run) is just `socklog-ucspi`?

**Comment by tokiclover** [comment]
If you want a particular socklog backend; unix/ucspi etc, you shall consolut the manual page to knwo how to add new instance (depend if using a static `/service/` or not.) If static service is used just `cp -a sv/syslog sv/socklog-ucspi` or else `ln -s syslog sv/socklog-uscpi`. And tada, done. That's all.
